---
- name: Setup listener for ACME http-01 challenges
  hosts: bigips
  connection: local
  gather_facts: false
  vars: 
  tasks:
    - debug:
        msg: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
    - name: Create declaration for pool and policy in Common
      template: 
        src: "{{ playbook_dir }}/acmelistenerpool.json.j2"
        dest: "{{ playbook_dir }}/{{ inventory_hostname }}acmeas3.json"
    - name: Post AS3 declaration to BIG-IPs
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        provider: "{{ atc_provider }}"
        atc_method: POST
        atc_declaration_file: "{{ playbook_dir }}/{{ inventory_hostname }}acmeas3.json"
        atc_service: AS3
